/**
 * gen-docs.ts — generates spec/REFERENCE.md from the canonical spec.json.
 *
 * This is the machine-faithful element/attribute reference: it is generated from
 * the same spec.json the kit and website read, so it can never drift from the
 * implementation. The prose/normative spec (spec/DOTGUI.md) stays hand-authored
 * and carries rationale this reference does not.
 *
 * Source of spec.json: spec/spec.json (generated by gen-spec.ts).
 * Run: bun run gen:docs   (or: node scripts/gen-docs.ts)
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const specPath = resolve(here, '../spec/spec.json')
const outPath = resolve(here, '../spec/REFERENCE.md')

interface Attr { name: string; type: string; required: boolean; description: string; enum?: string[] }
interface Element {
  slug: string; tag: string | null; name: string; kind: string; category: string
  summary: string; description: string[]; note?: string; mapsToFigma?: string
  attributes: Attr[]; sharedAttrs: boolean; example: string; exampleLabel: string
  related: string[]; faq: { q: string; a: string }[]
}
interface Spec { formatVersion: string; categoryOrder: string[]; sharedAttributes: Attr[]; elements: Element[] }

const spec: Spec = JSON.parse(readFileSync(specPath, 'utf8'))

const clean = (s: string) => s.replace(/[<>]/g, '')
const cell = (s: string) => (s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
const valueOf = (a: Attr) => (a.enum && a.enum.length ? a.enum.map(v => `\`${v}\``).join(' ') : `\`${a.type}\``)

function attrTable(attrs: Attr[]): string {
  if (!attrs.length) return ''
  const rows = attrs.map(a =>
    `| \`${a.name}\`${a.required ? ' **(required)**' : ''} | ${valueOf(a)} | ${cell(a.description)} |`
  )
  return ['| Attribute | Type | Description |', '|---|---|---|', ...rows].join('\n')
}

const lines: string[] = []
lines.push('<!-- GENERATED by scripts/gen-docs.ts — DO NOT EDIT. Source: kit spec.json. -->')
lines.push('')
lines.push('# .gui Element Reference')
lines.push('')
lines.push(`Format version \`${spec.formatVersion}\`. This reference is generated from the canonical spec — every element, attribute, type, and constraint is extracted from \`kit/src/schema/types.ts\`. For rationale and design philosophy, see [DOTGUI.md](DOTGUI.md).`)
lines.push('')

// Table of contents
lines.push('## Contents')
lines.push('')
for (const category of spec.categoryOrder) {
  const items = spec.elements.filter(e => e.category === category)
  if (!items.length) continue
  lines.push(`- **${category}** — ${items.map(e => `[${clean(e.name)}](#${e.slug})`).join(', ')}`)
}
lines.push('')

// Shared attributes
lines.push('## Shared attributes')
lines.push('')
lines.push('Available on all layout, content, and geometry nodes.')
lines.push('')
lines.push(attrTable(spec.sharedAttributes))
lines.push('')

// Elements by category
for (const category of spec.categoryOrder) {
  const items = spec.elements.filter(e => e.category === category)
  if (!items.length) continue
  lines.push(`## ${category}`)
  lines.push('')
  for (const el of items) {
    lines.push(`<a id="${el.slug}"></a>`)
    lines.push(`### ${clean(el.name)} <sup>${el.kind}</sup>`)
    lines.push('')
    if (el.summary) lines.push(`*${el.summary}*`)
    lines.push('')
    for (const p of el.description) lines.push(p, '')
    if (el.mapsToFigma) lines.push(`**Maps to Figma:** ${el.mapsToFigma}`, '')
    if (el.note) lines.push(`> ${el.note}`, '')
    const t = attrTable(el.attributes)
    if (t) lines.push(t, '')
    if (el.sharedAttrs) lines.push('Also accepts all [shared attributes](#shared-attributes).', '')
    if (el.example) {
      lines.push(`**${el.exampleLabel || 'Example'}**`, '')
      lines.push('```xml', el.example, '```', '')
    }
    if (el.faq && el.faq.length) {
      for (const f of el.faq) lines.push(`**${f.q}**`, '', f.a, '')
    }
    if (el.related && el.related.length) {
      lines.push(`*Related: ${el.related.map(r => `[${r}](#${r})`).join(', ')}*`, '')
    }
  }
}

writeFileSync(outPath, lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n')
console.log(`✓ REFERENCE.md written: ${spec.elements.length} elements, ${spec.sharedAttributes.length} shared attributes`)
